before_script:
    - if [ -f .docker-bootstrap.sh ]; then bash .docker-bootstrap.sh > /dev/null; fi
    - curl -O http://getcomposer.org/composer.phar
    - if [ "$SYMFONY_VERSION" != "" ]; then php composer.phar require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - php composer.phar update --prefer-dist --no-interaction

.test:units: &test_units
    stage: test
    script:
        - vendor/bin/atoum
    tags:
        - docker

test:sf27:
    <<: *test_units
    image: php:5.6
    variables:
        SYMFONY_VERSION: 2.7.*

test:sf28:
    <<: *test_units
    image: php:5.6
    variables:
        SYMFONY_VERSION: 2.8.*

test:sf30:
    <<: *test_units
    image: php:5.6
    variables:
        SYMFONY_VERSION: 3.0.*

test:sf31:
    <<: *test_units
    image: php:5.6
    variables:
        SYMFONY_VERSION: 3.1.*

test:php7.0:
    <<: *test_units
    image: php:7.0
